services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: customers
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db
  hotbed4stores-api:
    container_name: hotbed4stores-api
    image: rogelocard/hotbed4stores-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customers
      SPRING_DATASOURCE_USERNAME: amigoscode
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8088:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
